name: Notify MessageFlow Aggregator
on:
  push:
    branches: [ main ]

jobs:
  notify-messageflow-aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger aggregator‑repo workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.INTEGRATION_PAT }}
          repository: holydocs/messageflow-aggregator-action-example
          event-type: source-update
          client-payload: |
            {
              "source_repo": "${{ github.repository }}",
              "source_sha":  "${{ github.sha }}"
            }
